/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface ChainlinkVerifierInterface extends utils.Interface {
  functions: {
    "getName()": FunctionFragment;
    "getStatusFromRegistry()": FunctionFragment;
    "name()": FunctionFragment;
    "registryAddress()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getName"
      | "getStatusFromRegistry"
      | "name"
      | "registryAddress"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "getName", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getStatusFromRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registryAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "getName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getStatusFromRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registryAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ChainlinkVerifier extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ChainlinkVerifierInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getName(overrides?: CallOverrides): Promise<[string]>;

    getStatusFromRegistry(overrides?: CallOverrides): Promise<[string]>;

    name(overrides?: CallOverrides): Promise<[string]>;

    registryAddress(overrides?: CallOverrides): Promise<[string]>;
  };

  getName(overrides?: CallOverrides): Promise<string>;

  getStatusFromRegistry(overrides?: CallOverrides): Promise<string>;

  name(overrides?: CallOverrides): Promise<string>;

  registryAddress(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    getName(overrides?: CallOverrides): Promise<string>;

    getStatusFromRegistry(overrides?: CallOverrides): Promise<string>;

    name(overrides?: CallOverrides): Promise<string>;

    registryAddress(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getName(overrides?: CallOverrides): Promise<BigNumber>;

    getStatusFromRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    registryAddress(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getStatusFromRegistry(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registryAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
