version: '3'
networks:
  zkssi:
    driver: bridge

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - zkssi

  api0:
    build:
      dockerfile: Dockerfile.api
    ports:
      - "3000:8000"
    depends_on:
      - mongo
    environment:
      - ID=0
      - TYPE=api
      - API_URL=http://api0:3000
      - MONGO_URL=mongodb://mongo:27017
    volumes:
      - ../data_apis:/app/data_apis
      - ../deployments:/app/deployments
      - ../zkcdid-lib-rs:/app/zkcdid-lib-rs
    networks:
      - zkssi
    working_dir: /app/data_apis
    command: ["cargo", "watch", "-x", "run"]

  # oracle0:
  #   build:
  #     dockerfile: Dockerfile.oracle
  #   depends_on:
  #     - mongo
  #   networks:
  #     - zkssi
  #   volumes:
  #     - ../zk_oracles:/app/zk_oracles
  #     - ../deployments:/app/deployments
  #     - ../zkcdid-lib-rs:/app/zkcdid-lib-rs
  #   environment:
  #     - ID=0
  #     - TYPE=oracle
  #     - PRIVATE_KEY=${PRIVATE_KEY}
  #     - MONGO_URL=mongodb://mongo:27017
  #   command: ["cargo", "watch", "-x", "run --bin server"]

  # oracle0_listener:
  #   build:
  #     dockerfile: Dockerfile.oracle
  #   depends_on:
  #     - mongo
  #   networks:
  #     - zkssi
  #   volumes:
  #     - ../zk_oracles:/app/zk_oracles
  #     - ../deployments:/app/deployments
  #     - ../zkcdid-lib-rs:/app/zkcdid-lib-rs
  #   environment:
  #     - ID=0
  #     - TYPE=oracle
  #     - PRIVATE_KEY=${PRIVATE_KEY}
  #     - MONGO_URL=mongodb://mongo:27017
  #   command: ["cargo", "watch", "-x", "run --bin listener"]

  # oracle1:
  #   build:
  #     dockerfile: Dockerfile.oracle
  #   depends_on:
  #     - mongo
  #   networks:
  #     - zkssi
  #   volumes:
  #     - ../zk_oracles:/app/zk_oracles
  #     - ../deployments:/app/deployments
  #     - ../zkcdid-lib-rs:/app/zkcdid-lib-rs
  #   environment:
  #     - ID=1
  #     - TYPE=oracle
  #     - PRIVATE_KEY=${PRIVATE_KEY}
  #     - MONGO_URL=mongodb://mongo:27017
  #   command: ["cargo", "watch", "-x", "run --bin server"]

  # oracle1_listener:
  #   build:
  #     dockerfile: Dockerfile.oracle
  #   depends_on:
  #     - mongo
  #   networks:
  #     - zkssi
  #   volumes:
  #     - ../zk_oracles:/app/zk_oracles
  #     - ../deployments:/app/deployments
  #     - ../zkcdid-lib-rs:/app/zkcdid-lib-rs
  #   environment:
  #     - ID=1
  #     - TYPE=oracle
  #     - PRIVATE_KEY=${PRIVATE_KEY}
  #     - MONGO_URL=mongodb://mongo:27017
  #   command: ["cargo", "watch", "-x", "run --bin listener"]