/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IStatusRegistry,
  IStatusRegistryInterface,
} from "../../../contracts/ChainlinkVerifier.sol/IStatusRegistry";

const _abi = [
  {
    inputs: [],
    name: "getLastStatus",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IStatusRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IStatusRegistryInterface {
    return new utils.Interface(_abi) as IStatusRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IStatusRegistry {
    return new Contract(address, _abi, signerOrProvider) as IStatusRegistry;
  }
}
