/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FunctionsConsumer } from "./FunctionsConsumer";
export type { StatusRegistry } from "./StatusRegistry";
