# Stage 1: Build the Rust application
FROM rust:latest

# Create a new directory for the app and set it as the working directory
WORKDIR /app

# Install
RUN cargo install cargo-watch

# # Copy the entire project source code
# COPY . .

# Expose port for the web API
EXPOSE 8000


CMD ["sh", "-c", "cargo watch -x run"]
